# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CronometroDialog
                                 A QGIS plugin
 Crea un cronometro
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-11
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Korto19
        email                : a@a.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import datetime
import time

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Cronometro_dialog_base.ui'))


class CronometroDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(CronometroDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # counter
        self.count = 0

        # creating flag
        self.flag = False
        
        text = str(datetime.timedelta(seconds=int(self.count/10)))
        # showing text
        self.label.setText(text)

    def closeEvent(self, event):
       #print("User has clicked the red x on the main window")
       event.accept()